name: Render
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install deps
        run: Rscript install.R
      - name: Setup Kaggle
        run: bash scripts/setup_kaggle.sh
      - name: Render
        run: quarto render quarto/learning_lsa_lda.qmd
      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
